import Head from 'next/head'
import Script from 'next/Script'
import AppFooter from './blocks/app-footer'
import Headernav from './blocks/header-nav'


export default function Blogsingle () {
    return (
    <>
        <Head>
            <title>Soft Land | Features</title>
            <meta name="description" content="Generated by create next app" />
            <link rel="icon" href="/assets/favicon.ico" />
            <link href="/assets/img/favicon.png" rel="icon" />
            <link href="/assets/img/apple-touch-icon.png" rel="apple-touch-icon" />
            <link
                href="https://fonts.googleapis.com/css?family=Roboto:300,300i,400,400i,500,500i,600,600i,700,700i|Poppins:300,300i,400,400i,500,500i,600,600i,700,700i"
                rel="stylesheet"
            />
            <link href="/assets/vendor/aos/aos.css" rel="stylesheet" />
            <link
                href="/assets/vendor/bootstrap/css/bootstrap.min.css"
                rel="stylesheet"
            />
            <link
                href="/assets/vendor/bootstrap-icons/bootstrap-icons.css"
                rel="stylesheet"
            />
            <link href="/assets/vendor/boxicons/css/boxicons.min.css" rel="stylesheet" />
            <link href="/assets/vendor/swiper/swiper-bundle.min.css" rel="stylesheet" />
            <link href="/assets/css/style.css" rel="stylesheet" />
        </Head>
        <Headernav />
        <>
  <main id="main">
    {/* ======= Single Blog Section ======= */}
    <section className="hero-section inner-page">
      <div className="wave">
        <svg
          width="1920px"
          height="265px"
          viewBox="0 0 1920 265"
          version="1.1"
          xmlns="http://www.w3.org/2000/svg"
          xmlnsXlink="http://www.w3.org/1999/xlink"
        >
          <g
            id="Page-1"
            stroke="none"
            strokeWidth={1}
            fill="none"
            fillRule="evenodd"
          >
            <g
              id="Apple-TV"
              transform="translate(0.000000, -402.000000)"
              fill="#FFFFFF"
            >
              <path
                d="M0,439.134243 C175.04074,464.89273 327.944386,477.771974 458.710937,477.771974 C654.860765,477.771974 870.645295,442.632362 1205.9828,410.192501 C1429.54114,388.565926 1667.54687,411.092417 1920,477.771974 L1920,667 L1017.15166,667 L0,667 L0,439.134243 Z"
                id="Path"
              />
            </g>
          </g>
        </svg>
      </div>
      <div className="container">
        <div className="row align-items-center">
          <div className="col-12">
            <div className="row justify-content-center">
              <div className="col-md-10 text-center hero-text">
                <h1 data-aos="fade-up" data-aos-delay="">
                  Chrome now alerts you when someone steals your password
                </h1>
                <p className="mb-5" data-aos="fade-up" data-aos-delay={100}>
                  December 13, 2019 • By{" "}
                  <a href="#" className="text-white">
                    Admin
                  </a>
                </p>
              </div>
            </div>
          </div>
        </div>
      </div>
    </section>
    <section className="site-section mb-4">
      <div className="container">
        <div className="row">
          <div className="col-md-8 blog-content">
            <p className="lead mb-5">
              Lorem ipsum dolor sit amet, consectetur adipisicing elit.
              Assumenda nihil aspernatur nemo sunt, qui, harum repudiandae
              quisquam eaque dolore itaque quod tenetur quo quos labore?
            </p>
            <p>
              Lorem ipsum dolor sit amet, consectetur adipisicing elit. Quae
              expedita cumque necessitatibus ducimus debitis totam, quasi
              praesentium eveniet tempore possimus illo esse, facilis? Corrupti
              possimus quae ipsa pariatur cumque, accusantium tenetur
              voluptatibus incidunt reprehenderit, quidem repellat sapiente, id,
              earum obcaecati.
            </p>
            <div className="row mb-5">
              <div className="col-md-6">
                <figure>
                  <img
                    src="assets/img/img_1.jpg"
                    alt="Free Website Template by Free-Template.co"
                    className="img-fluid"
                  />
                  <figcaption>This is an image caption</figcaption>
                </figure>
              </div>
              <div className="col-md-6">
                <figure>
                  <img
                    src="assets/img/img_2.jpg"
                    alt="Free Website Template by Free-Template.co"
                    className="img-fluid"
                  />
                  <figcaption>This is an image caption</figcaption>
                </figure>
              </div>
            </div>
            <blockquote>
              <p>
                Lorem ipsum dolor sit amet, consectetur adipisicing elit.
                Provident vero tempora aliquam excepturi labore, ad soluta
                voluptate necessitatibus. Nulla error beatae, quam, facilis
                suscipit quaerat aperiam minima eveniet quis placeat.
              </p>
            </blockquote>
            <p>
              Eveniet deleniti accusantium nulla natus nobis nam asperiores ipsa
              minima laudantium vero cumque cupiditate ipsum ratione dicta,
              expedita quae, officiis provident harum nisi! Esse eligendi ab
              molestias, quod nostrum hic saepe repudiandae non. Suscipit
              reiciendis tempora ut, saepe temporibus nemo.
            </p>
            <p>
              Accusamus, temporibus, ullam. Voluptate consectetur laborum totam
              sunt culpa repellat, dolore voluptas. Quaerat cum ducimus aut
              distinctio sit, facilis corporis ab vel alias, voluptas aliquam,
              expedita molestias quisquam sequi eligendi nobis ea error omnis
              consequatur iste deleniti illum, dolorum odit.
            </p>
            <p>
              In adipisci corporis at delectus! Cupiditate, voluptas, in
              architecto odit id error reprehenderit quam quibusdam excepturi
              distinctio dicta laborum deserunt qui labore dignissimos
              necessitatibus reiciendis tenetur corporis quas explicabo
              exercitationem suscipit. Nisi quo nulla, nihil harum obcaecati vel
              atque quos.
            </p>
            <p>
              Amet sint explicabo maxime accusantium qui dicta enim quia,
              nostrum id libero voluptates quae suscipit dolor quam tenetur
              dolores inventore illo laborum, corporis non ex, debitis quidem
              obcaecati! Praesentium maiores illo atque error! Earum, et, fugit.
              Sint, delectus molestiae. Totam.
            </p>
            <p>
              Lorem ipsum dolor sit amet, consectetur adipisicing elit. Culpa
              iste, repudiandae facere aperiam sapiente, officia delectus soluta
              molestiae nihil corporis animi quos ratione qui labore? Sint eaque
              perspiciatis minus illum.
            </p>
            <p>
              Consectetur porro odio quod iure quaerat cupiditate similique,
              dolor reprehenderit molestias provident, esse dolorum omnis
              architecto magni amet corrupti neque ratione sunt beatae
              perspiciatis? Iste pariatur omnis sed ut itaque.
            </p>
            <p>
              Id similique, rem ipsam accusantium iusto dolores sit velit ex
              quas ea atque, molestiae. Sint, sed. Quisquam, suscipit! Quisquam
              quibusdam maiores fugiat eligendi eius consequuntur, molestiae
              saepe commodi expedita nemo!
            </p>
            <div className="pt-5">
              <p>
                Categories: <a href="#">Design</a>, <a href="#">Events</a> Tags:{" "}
                <a href="#">#html</a>, <a href="#">#trends</a>
              </p>
            </div>
            <div className="pt-5">
              <h3 className="mb-5">6 Comments</h3>
              <ul className="comment-list">
                <li className="comment">
                  <div className="vcard bio">
                    <img
                      src="assets/img/person_1.jpg"
                      alt="Free Website Template by Free-Template.co"
                    />
                  </div>
                  <div className="comment-body">
                    <h3>Jean Doe</h3>
                    <div className="meta">January 9, 2018 at 2:21pm</div>
                    <p>
                      Lorem ipsum dolor sit amet, consectetur adipisicing elit.
                      Pariatur quidem laborum necessitatibus, ipsam impedit
                      vitae autem, eum officia, fugiat saepe enim sapiente iste
                      iure! Quam voluptas earum impedit necessitatibus, nihil?
                    </p>
                    <p>
                      <a href="#" className="reply">
                        Reply
                      </a>
                    </p>
                  </div>
                </li>
                <li className="comment">
                  <div className="vcard bio">
                    <img
                      src="assets/img/person_1.jpg"
                      alt="Image placeholder"
                    />
                  </div>
                  <div className="comment-body">
                    <h3>Jean Doe</h3>
                    <div className="meta">January 9, 2018 at 2:21pm</div>
                    <p>
                      Lorem ipsum dolor sit amet, consectetur adipisicing elit.
                      Pariatur quidem laborum necessitatibus, ipsam impedit
                      vitae autem, eum officia, fugiat saepe enim sapiente iste
                      iure! Quam voluptas earum impedit necessitatibus, nihil?
                    </p>
                    <p>
                      <a href="#" className="reply">
                        Reply
                      </a>
                    </p>
                  </div>
                  <ul className="children">
                    <li className="comment">
                      <div className="vcard bio">
                        <img
                          src="assets/img/person_1.jpg"
                          alt="Image placeholder"
                        />
                      </div>
                      <div className="comment-body">
                        <h3>Jean Doe</h3>
                        <div className="meta">January 9, 2018 at 2:21pm</div>
                        <p>
                          Lorem ipsum dolor sit amet, consectetur adipisicing
                          elit. Pariatur quidem laborum necessitatibus, ipsam
                          impedit vitae autem, eum officia, fugiat saepe enim
                          sapiente iste iure! Quam voluptas earum impedit
                          necessitatibus, nihil?
                        </p>
                        <p>
                          <a href="#" className="reply">
                            Reply
                          </a>
                        </p>
                      </div>
                      <ul className="children">
                        <li className="comment">
                          <div className="vcard bio">
                            <img
                              src="assets/img/person_1.jpg"
                              alt="Image placeholder"
                            />
                          </div>
                          <div className="comment-body">
                            <h3>Jean Doe</h3>
                            <div className="meta">
                              January 9, 2018 at 2:21pm
                            </div>
                            <p>
                              Lorem ipsum dolor sit amet, consectetur
                              adipisicing elit. Pariatur quidem laborum
                              necessitatibus, ipsam impedit vitae autem, eum
                              officia, fugiat saepe enim sapiente iste iure!
                              Quam voluptas earum impedit necessitatibus, nihil?
                            </p>
                            <p>
                              <a href="#" className="reply">
                                Reply
                              </a>
                            </p>
                          </div>
                          <ul className="children">
                            <li className="comment">
                              <div className="vcard bio">
                                <img
                                  src="assets/img/person_1.jpg"
                                  alt="Image placeholder"
                                />
                              </div>
                              <div className="comment-body">
                                <h3>Jean Doe</h3>
                                <div className="meta">
                                  January 9, 2018 at 2:21pm
                                </div>
                                <p>
                                  Lorem ipsum dolor sit amet, consectetur
                                  adipisicing elit. Pariatur quidem laborum
                                  necessitatibus, ipsam impedit vitae autem, eum
                                  officia, fugiat saepe enim sapiente iste iure!
                                  Quam voluptas earum impedit necessitatibus,
                                  nihil?
                                </p>
                                <p>
                                  <a href="#" className="reply">
                                    Reply
                                  </a>
                                </p>
                              </div>
                            </li>
                          </ul>
                        </li>
                      </ul>
                    </li>
                  </ul>
                </li>
                <li className="comment">
                  <div className="vcard bio">
                    <img
                      src="assets/img/person_1.jpg"
                      alt="Image placeholder"
                    />
                  </div>
                  <div className="comment-body">
                    <h3>Jean Doe</h3>
                    <div className="meta">January 9, 2018 at 2:21pm</div>
                    <p>
                      Lorem ipsum dolor sit amet, consectetur adipisicing elit.
                      Pariatur quidem laborum necessitatibus, ipsam impedit
                      vitae autem, eum officia, fugiat saepe enim sapiente iste
                      iure! Quam voluptas earum impedit necessitatibus, nihil?
                    </p>
                    <p>
                      <a href="#" className="reply">
                        Reply
                      </a>
                    </p>
                  </div>
                </li>
              </ul>
              {/* END comment-list */}
              <div className="comment-form-wrap pt-5">
                <h3 className="mb-5">Leave a comment</h3>
                <form action="#" className="">
                  <div className="form-group">
                    <label htmlFor="name">Name *</label>
                    <input type="text" className="form-control" id="name" />
                  </div>
                  <div className="form-group mt-3">
                    <label htmlFor="email">Email *</label>
                    <input type="email" className="form-control" id="email" />
                  </div>
                  <div className="form-group mt-3">
                    <label htmlFor="website">Website</label>
                    <input type="url" className="form-control" id="website" />
                  </div>
                  <div className="form-group mt-3">
                    <label htmlFor="message">Message</label>
                    <textarea
                      name=""
                      id="message"
                      cols={30}
                      rows={10}
                      className="form-control"
                      defaultValue={""}
                    />
                  </div>
                  <div className="form-group mt-3">
                    <input
                      type="submit"
                      defaultValue="Post Comment"
                      className="btn btn-primary"
                    />
                  </div>
                </form>
              </div>
            </div>
          </div>
          <div className="col-md-4 sidebar">
            <div className="sidebar-box">
              <form action="#" className="search-form">
                <div className="form-group">
                  <span className="icon fa fa-search" />
                  <input
                    type="text"
                    className="form-control"
                    placeholder="Type a keyword and hit enter"
                  />
                </div>
              </form>
            </div>
            <div className="sidebar-box">
              <div className="categories">
                <h3>Categories</h3>
                <li>
                  <a href="#">
                    Dog <span>(12)</span>
                  </a>
                </li>
                <li>
                  <a href="#">
                    Dog Food <span>(22)</span>
                  </a>
                </li>
                <li>
                  <a href="#">
                    Vetenirarian <span>(37)</span>
                  </a>
                </li>
                <li>
                  <a href="#">
                    Events<span>(42)</span>
                  </a>
                </li>
              </div>
            </div>
            <div className="sidebar-box">
              <img
                src="assets/img/person_1.jpg"
                alt="Image placeholder"
                className="img-fluid mb-4"
              />
              <h3>About The Author</h3>
              <p>
                Lorem ipsum dolor sit amet, consectetur adipisicing elit.
                Ducimus itaque, autem necessitatibus voluptate quod mollitia
                delectus aut, sunt placeat nam vero culpa sapiente consectetur
                similique, inventore eos fugit cupiditate numquam!
              </p>
              <p>
                <a href="#" className="btn btn-primary btn-sm">
                  Read More
                </a>
              </p>
            </div>
            <div className="sidebar-box">
              <h3>Paragraph</h3>
              <p>
                Lorem ipsum dolor sit amet, consectetur adipisicing elit.
                Ducimus itaque, autem necessitatibus voluptate quod mollitia
                delectus aut, sunt placeat nam vero culpa sapiente consectetur
                similique, inventore eos fugit cupiditate numquam!
              </p>
            </div>
          </div>
        </div>
      </div>
    </section>
    {/* ======= CTA Section ======= */}
    <section className="section cta-section">
      <div className="container">
        <div className="row align-items-center">
          <div className="col-md-6 me-auto text-center text-md-start mb-5 mb-md-0">
            <h2>Starts Publishing Your Apps</h2>
          </div>
          <div className="col-md-5 text-center text-md-end">
            <p>
              <a href="#" className="btn d-inline-flex align-items-center">
                <i className="bx bxl-apple" />
                <span>App store</span>
              </a>{" "}
              <a href="#" className="btn d-inline-flex align-items-center">
                <i className="bx bxl-play-store" />
                <span>Google play</span>
              </a>
            </p>
          </div>
        </div>
      </div>
    </section>
    {/* End CTA Section */}
  </main>
  {/* End #main */}
</>


        <AppFooter />

        <a href="#" className="back-to-top d-flex align-items-center justify-content-center"><i className="bi bi-arrow-up-short"></i></a>
    <Script src="/assets/vendor/aos/aos.js"></Script>
    <Script src="/assets/vendor/bootstrap/js/bootstrap.bundle.min.js"></Script>
    <Script src="assets/vendor/swiper/swiper-bundle.min.js"></Script>
    <Script src="/assets/vendor/php-email-form/validate.js"></Script>
    <Script src="/assets/js/main.js"></Script>
    </>

    ) 
}
    



