import Head from 'next/head'
import Script from 'next/Script'
import Headernav from './blocks/header-nav'



export default function Home() {
  return (
  <>
  <Head>
    <title>Soft Land | Home</title>
    <meta name="description" content="Generated by create next app" />
    <link rel="icon" href="/assets/favicon.ico" />
    <link href="/assets/img/favicon.png" rel="icon" />
    <link href="/assets/img/apple-touch-icon.png" rel="apple-touch-icon" />
    <link
      href="https://fonts.googleapis.com/css?family=Roboto:300,300i,400,400i,500,500i,600,600i,700,700i|Poppins:300,300i,400,400i,500,500i,600,600i,700,700i"
      rel="stylesheet"
    />
    <link href="/assets/vendor/aos/aos.css" rel="stylesheet" />
    <link
      href="/assets/vendor/bootstrap/css/bootstrap.min.css"
      rel="stylesheet"
    />
    <link
      href="/assets/vendor/bootstrap-icons/bootstrap-icons.css"
      rel="stylesheet"
    />
    <link href="/assets/vendor/boxicons/css/boxicons.min.css" rel="stylesheet" />
    <link href="/assets/vendor/swiper/swiper-bundle.min.css" rel="stylesheet" />
    <link href="/assets/css/style.css" rel="stylesheet" />
  </Head>
  <>
  {/* ======= Header ======= */}
  <Headernav />
  {/* End Header */}
  {/* ======= Hero Section ======= */}
  <section className="hero-section" id="hero">
    <div className="wave">
      <svg
        width="100%"
        height="355px"
        viewBox="0 0 1920 355"
        version="1.1"
        xmlns="http://www.w3.org/2000/svg"
        xmlnsXlink="http://www.w3.org/1999/xlink"
      >
        <g
          id="Page-1"
          stroke="none"
          strokeWidth={1}
          fill="none"
          fillRule="evenodd"
        >
          <g
            id="Apple-TV"
            transform="translate(0.000000, -402.000000)"
            fill="#FFFFFF"
          >
            <path
              d="M0,439.134243 C175.04074,464.89273 327.944386,477.771974 458.710937,477.771974 C654.860765,477.771974 870.645295,442.632362 1205.9828,410.192501 C1429.54114,388.565926 1667.54687,411.092417 1920,477.771974 L1920,757 L1017.15166,757 L0,757 L0,439.134243 Z"
              id="Path"
            />
          </g>
        </g>
      </svg>
    </div>
    <div className="container">
      <div className="row align-items-center">
        <div className="col-12 hero-text-image">
          <div className="row">
            <div className="col-lg-8 text-center text-lg-start">
              <h1 data-aos="fade-right">Promote Your App with SoftLand</h1>
              <p className="mb-5" data-aos="fade-right" data-aos-delay={100}>
                Lorem ipsum dolor sit amet, consectetur adipisicing elit.
              </p>
              <p
                data-aos="fade-right"
                data-aos-delay={200}
                data-aos-offset={-500}
              >
                <a href="#" className="btn btn-outline-white">
                  Get started
                </a>
              </p>
            </div>
            <div className="col-lg-4 iphone-wrap">
              <img
                src="assets/img/phone_1.png"
                alt="Image"
                className="phone-1"
                data-aos="fade-right"
              />
              <img
                src="assets/img/phone_2.png"
                alt="Image"
                className="phone-2"
                data-aos="fade-right"
                data-aos-delay={200}
              />
            </div>
          </div>
        </div>
      </div>
    </div>
  </section>
  {/* End Hero */}
  <main id="main">
    {/* ======= Home Section ======= */}
    <section className="section">
      <div className="container">
        <div className="row justify-content-center text-center mb-5">
          <div className="col-md-5" data-aos="fade-up">
            <h2 className="section-heading">
              Save your time to using SoftLand
            </h2>
          </div>
        </div>
        <div className="row">
          <div className="col-md-4" data-aos="fade-up" data-aos-delay="">
            <div className="feature-1 text-center">
              <div className="wrap-icon icon-1">
                <i className="bi bi-people" />
              </div>
              <h3 className="mb-3">Explore Your Team</h3>
              <p>
                Lorem ipsum dolor sit amet, consectetur adipisicing elit. Rem,
                optio.
              </p>
            </div>
          </div>
          <div className="col-md-4" data-aos="fade-up" data-aos-delay={100}>
            <div className="feature-1 text-center">
              <div className="wrap-icon icon-1">
                <i className="bi bi-brightness-high" />
              </div>
              <h3 className="mb-3">Digital Whiteboard</h3>
              <p>
                Lorem ipsum dolor sit amet, consectetur adipisicing elit. Rem,
                optio.
              </p>
            </div>
          </div>
          <div className="col-md-4" data-aos="fade-up" data-aos-delay={200}>
            <div className="feature-1 text-center">
              <div className="wrap-icon icon-1">
                <i className="bi bi-bar-chart" />
              </div>
              <h3 className="mb-3">Design To Development</h3>
              <p>
                Lorem ipsum dolor sit amet, consectetur adipisicing elit. Rem,
                optio.
              </p>
            </div>
          </div>
        </div>
      </div>
    </section>
    <section className="section">
      <div className="container">
        <div
          className="row justify-content-center text-center mb-5"
          data-aos="fade"
        >
          <div className="col-md-6 mb-5">
            <img
              src="assets/img/undraw_svg_1.svg"
              alt="Image"
              className="img-fluid"
            />
          </div>
        </div>
        <div className="row">
          <div className="col-md-4">
            <div className="step">
              <span className="number">01</span>
              <h3>Sign Up</h3>
              <p>
                Lorem ipsum dolor sit amet, consectetur adipisicing elit. Rem,
                optio.
              </p>
            </div>
          </div>
          <div className="col-md-4">
            <div className="step">
              <span className="number">02</span>
              <h3>Create Profile</h3>
              <p>
                Lorem ipsum dolor sit amet, consectetur adipisicing elit. Rem,
                optio.
              </p>
            </div>
          </div>
          <div className="col-md-4">
            <div className="step">
              <span className="number">03</span>
              <h3>Enjoy the app</h3>
              <p>
                Lorem ipsum dolor sit amet, consectetur adipisicing elit. Rem,
                optio.
              </p>
            </div>
          </div>
        </div>
      </div>
    </section>
    <section className="section">
      <div className="container">
        <div className="row align-items-center">
          <div className="col-md-4 me-auto">
            <h2 className="mb-4">Seamlessly Communicate</h2>
            <p className="mb-4">
              Lorem ipsum dolor sit amet, consectetur adipisicing elit. Tenetur
              at reprehenderit optio, laudantium eius quod, eum maxime molestiae
              porro omnis. Dolores aspernatur delectus impedit incidunt dolore
              mollitia esse natus beatae.
            </p>
            <p>
              <a href="#" className="btn btn-primary">
                Download Now
              </a>
            </p>
          </div>
          <div className="col-md-6" data-aos="fade-left">
            <img
              src="assets/img/undraw_svg_2.svg"
              alt="Image"
              className="img-fluid"
            />
          </div>
        </div>
      </div>
    </section>
    <section className="section">
      <div className="container">
        <div className="row align-items-center">
          <div className="col-md-4 ms-auto order-2">
            <h2 className="mb-4">Gather Feedback</h2>
            <p className="mb-4">
              Lorem ipsum dolor sit amet, consectetur adipisicing elit. Tenetur
              at reprehenderit optio, laudantium eius quod, eum maxime molestiae
              porro omnis. Dolores aspernatur delectus impedit incidunt dolore
              mollitia esse natus beatae.
            </p>
            <p>
              <a href="#" className="btn btn-primary">
                Download Now
              </a>
            </p>
          </div>
          <div className="col-md-6" data-aos="fade-right">
            <img
              src="assets/img/undraw_svg_3.svg"
              alt="Image"
              className="img-fluid"
            />
          </div>
        </div>
      </div>
    </section>
    {/* ======= Testimonials Section ======= */}
   
    {/* End Testimonials Section */}
    {/* ======= CTA Section ======= */}
    <section className="section cta-section">
      <div className="container">
        <div className="row align-items-center">
          <div className="col-md-6 me-auto text-center text-md-start mb-5 mb-md-0">
            <h2>Starts Publishing Your Apps</h2>
          </div>
          <div className="col-md-5 text-center text-md-end">
            <p>
              <a href="#" className="btn d-inline-flex align-items-center">
                <i className="bx bxl-apple" />
                <span>App store</span>
              </a>{" "}
              <a href="#" className="btn d-inline-flex align-items-center">
                <i className="bx bxl-play-store" />
                <span>Google play</span>
              </a>
            </p>
          </div>
        </div>
      </div>
    </section>
    {/* End CTA Section */}
  </main>
  {/* End #main */}
  {/* ======= Footer ======= */}
  <footer className="footer" role="contentinfo">
    <div className="container">
      <div className="row">
        <div className="col-md-4 mb-4 mb-md-0">
          <h3>About SoftLand</h3>
          <p>
            Lorem ipsum dolor sit amet, consectetur adipisicing elit. Eius ea
            delectus pariatur, numquam aperiam dolore nam optio dolorem facilis
            itaque voluptatum recusandae deleniti minus animi.
          </p>
          <p className="social">
            <a href="#">
              <span className="bi bi-twitter" />
            </a>
            <a href="#">
              <span className="bi bi-facebook" />
            </a>
            <a href="#">
              <span className="bi bi-instagram" />
            </a>
            <a href="#">
              <span className="bi bi-linkedin" />
            </a>
          </p>
        </div>
        <div className="col-md-7 ms-auto">
          <div className="row site-section pt-0">
            <div className="col-md-4 mb-4 mb-md-0">
              <h3>Navigation</h3>
              <ul className="list-unstyled">
                <li>
                  <a href="#">Pricing</a>
                </li>
                <li>
                  <a href="#">Features</a>
                </li>
                <li>
                  <a href="#">Blog</a>
                </li>
                <li>
                  <a href="#">Contact</a>
                </li>
              </ul>
            </div>
            <div className="col-md-4 mb-4 mb-md-0">
              <h3>Services</h3>
              <ul className="list-unstyled">
                <li>
                  <a href="#">Team</a>
                </li>
                <li>
                  <a href="#">Collaboration</a>
                </li>
                <li>
                  <a href="#">Todos</a>
                </li>
                <li>
                  <a href="#">Events</a>
                </li>
              </ul>
            </div>
            <div className="col-md-4 mb-4 mb-md-0">
              <h3>Downloads</h3>
              <ul className="list-unstyled">
                <li>
                  <a href="#">Get from the App Store</a>
                </li>
                <li>
                  <a href="#">Get from the Play Store</a>
                </li>
              </ul>
            </div>
          </div>
        </div>
      </div>
      <div className="row justify-content-center text-center">
        <div className="col-md-7">
          <p className="copyright">© Copyright SoftLand. All Rights Reserved</p>
          <div className="credits">
            {/*
      All the links in the footer should remain intact.
      You can delete the links only if you purchased the pro version.
      Licensing information: https://bootstrapmade.com/license/
      Purchase the pro version with working PHP/AJAX contact form: https://bootstrapmade.com/buy/?theme=SoftLand
    */}
            Designed by <a href="https://bootstrapmade.com/">BootstrapMade</a>
          </div>
        </div>
      </div>
    </div>
  </footer>
  <a
    href="#"
    className="back-to-top d-flex align-items-center justify-content-center"
  >
    <i className="bi bi-arrow-up-short" />
  </a>
</>

      
      
    <a href="#" className="back-to-top d-flex align-items-center justify-content-center"><i className="bi bi-arrow-up-short"></i></a>
    <Script src="/assets/vendor/aos/aos.js"></Script>
    <Script src="/assets/vendor/bootstrap/js/bootstrap.bundle.min.js"></Script>
    <Script src="assets/vendor/swiper/swiper-bundle.min.js"></Script>
    <Script src="/assets/vendor/php-email-form/validate.js"></Script>
    <Script src="/assets/js/main.js"></Script>
    </>
  )
}
